version: '3.9'


services:
  psql:
    container_name: db
    image: 'postgres:14.1-alpine'
    ports:
      - '5432:5432'

    environment:
      - POSTGRES_PASSWORD=password
      - POSTGRES_USER=admin
      - POSTGRES_DB=postgres

    volumes:
      - ./data/db:/var/lib/postgresql/data/

