version: '3.9'


services:
  psql:
    container_name: db
    image: 'postgres:14.1-alpine'
    ports:
      - '5432:5432'

    environment:
      - POSTGRES_PASSWORD=password
      - POSTGRES_USER=admin
      - POSTGRES_DB=postgres

    volumes:
      - ./data/db:/var/lib/postgresql/data/

  frontend:
    container_name: web
    build:
      context: ./web
      dockerfile: Dockerfile

    ports:
      - '3000:3000'

    volumes:
      - ./web:/app/web

    depends_on:
      - backend

  backend:
    container_name: api
    build:
      context: ./api
      dockerfile: Dockerfile

    env_file:
      - ./api/.env

    ports:
      - '8000:8000'

    volumes:
      - ./api:/app/api

    depends_on:
      - psql
